port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, vendor]
include: ['surveys/', 'surveys/2015/', 'faq/']
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
#pygments is not supported by GitHub. See https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
#See also https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
#We have to use rouge
highlighter: rouge
# Hint by http://milanaryal.com/2015/writing-on-github-pages-and-jekyll-using-markdown/ and http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
#markdown: redcarpet
#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

### required for faq/
collections:
- faq

### content configuration ###
title:       "JabRef"
keywords:    "JabRef, bibtex, biblatex, bibliography, editor"
description: "Graphical Java application for managing bibtex (.bib) databases"
source_link: "https://github.com/JabRef/www.jabref.org/"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  lightgray: '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  jabref-font:     '#4d4674'
  light-turquoise: '#d0f7fb'
