name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: [completed]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prepare artifact
        run: |
          mkdir artifact
          npx tsc nuxt.config.ts || true
          cp -r .nuxt nuxt.config.js package.json /api artifact

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: JabRef
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./artifact

