on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and Deploy Jekyll
        uses: koppor/jekyll-deploy-gh-pages@patch-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .nojekyll
        run: touch build/.nojekyll
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: build
