on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and Deploy Jekyll
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: koppor/github-push-action@add-support-for-sub-directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: build
