on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build and Deploy Jekyll
        uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
