on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Create .nojekyll
        run: |
          mkdir build
          touch build/.nojekyll
      - name: Build and Deploy Jekyll
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: build
